INSERT INTO usuaris(ID, NOM, TIRADES, GUANYADES, PROMIG) VALUES (null, 'Joan Josep', 5, 2, 40);
INSERT INTO usuaris(ID, NOM, TIRADES, GUANYADES, PROMIG) VALUES (null, 'Toni Gonzalez', 4, 1, 25);
INSERT INTO usuaris(ID, NOM, TIRADES, GUANYADES, PROMIG) VALUES (null, 'Joana Sanchez', 3, 1, 33);
INSERT INTO usuaris(ID, NOM, TIRADES, GUANYADES, PROMIG) VALUES (null, 'Cristina Martinez', 6, 1, 16.6);


INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 2, 4, false, 1);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 3, 2, 5, false, 1);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 3, 4, 7, true, 1);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 1, 6, 7, true, 1);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 5, 4, 9, false, 1);

INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 5, 7, true, 2);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 1, 2, 3, false, 2);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 4, 6, false, 2);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 6, 3, 9, false, 2);

INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 5, 7, true, 3);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 2, 4, false, 3);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 1, 2, 3, false, 3);

INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 4, 3, 7, true, 4);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 2, 4, false, 4);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 6, 6, 12, false, 4);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 5, 5, 10, false, 4);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 2, 3, 5, false, 4);
INSERT INTO tirades(ID, VALOR1, VALOR2, VALORTOTAL, VICTORIA, USUARIID) VALUES (null, 4, 2, 6, false, 4);