DROP TABLE IF EXISTS TIRADES;

CREATE TABLE TIRADES(
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		VALOR1 INTEGER,
		VALOR2 INTEGER,
		VALORTOTAL INTEGER,
		VICTORIA BOOLEAN,
		USUARIID INTEGER
);

DROP TABLE IF EXISTS USUARIS; 

CREATE TABLE USUARIS(
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		NOM VARCHAR(255),
		TIRADES INTEGER,
		GUANYADES INTEGER,
		PROMIG DOUBLE
);

ALTER TABLE TIRADES
ADD FOREIGN KEY (usuariid) REFERENCES usuaris(id);